services:
  cron-practice:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - NAME=${NAME}
      - GREETING=${GREETING}
    volumes:
      - cron-practice:/app

volumes:
  cron-practice